import { UpgradeCard } from './types';

export const INITIAL_UPGRADE_POOL: UpgradeCard[] = [
  {
    id: 'bot_delivery',
    name: '送餐無人侍者 🤖',
    desc: '配備高精度導航的送餐機器人，自動將出餐檯的料理送至等候餐桌',
    cost: 75,
    icon: '🤖',
    tag: '智能科技',
    applied: false,
  },
  {
    id: 'bot_apprentice',
    name: '備料學徒助手 🍳',
    desc: '全自動廚房二廚，巡邏煎台防止燒焦，並自動在砧板切片起司與蔬菜',
    cost: 70,
    icon: '🧑‍🍳',
    tag: '智能科技',
    applied: false,
  },
  {
    id: 'service_bell',
    name: '黃金迎賓響鈴 🔔',
    desc: '按響金鐘（快捷鍵 Q 或按鈕），使全場等候顧客耐心值即刻回復 50%（每日 2 次）',
    cost: 45,
    icon: '🔔',
    tag: '主動技能',
    applied: false,
  },
  {
    id: 'magic_spice',
    name: '秘製靈魂香料 🧂',
    desc: '主廚特調香料！全料理出餐售價額外 +35%，且全顧客等待耐心流失速度 -30%',
    cost: 55,
    icon: '🧂',
    tag: '極品調味',
    applied: false,
  },
  {
    id: 'boots',
    name: '極速溜冰鞋 ⚡',
    desc: '主廚移動速度提升 30%，端盤如疾風',
    cost: 30,
    icon: '⚡',
    tag: '移動強化',
    applied: false,
  },
  {
    id: 'turbo_hob',
    name: '渦輪急速煎台 🔥',
    desc: '肉排烹飪時間減半，出餐效率倍增',
    cost: 45,
    icon: '🔥',
    tag: '烹飪倍速',
    applied: false,
  },
  {
    id: 'power_sink',
    name: '渦流強力水槽 💧',
    desc: '洗碗速度提升 120%，髒盤秒變潔淨',
    cost: 35,
    icon: '💧',
    tag: '洗碗加速',
    applied: false,
  },
  {
    id: 'dishwasher',
    name: '全自動浸泡洗碗機 🫧',
    desc: '放入水槽的髒盤子會自動持續清洗，無需主廚全程手動長按',
    cost: 60,
    icon: '🫧',
    tag: '自動化',
    applied: false,
  },
  {
    id: 'safe_hob',
    name: '恆溫安全防焦底 🛡️',
    desc: '煎台上的肉排煎熟後永不燒焦，烹飪零壓力',
    cost: 45,
    icon: '🛡️',
    tag: '防燒焦',
    applied: false,
  },
  {
    id: 'recipe_salad',
    name: '新菜譜：田園沙拉 🥗',
    desc: '解鎖田園鮮蔬沙拉！顧客開始點購沙拉，純刀工無油煙單價 $28',
    cost: 35,
    icon: '🥗',
    tag: '新食譜',
    applied: false,
  },
  {
    id: 'recipe_steak',
    name: '新菜譜：香煎牛排 🥩',
    desc: '解鎖頂級炙烤牛排配烤番茄！單份利潤高達 $42',
    cost: 50,
    icon: '🥩',
    tag: '新食譜',
    applied: false,
  },
  {
    id: 'recipe_deluxe',
    name: '新菜譜：豪華總匯堡 👑',
    desc: '解鎖頂級五層總匯漢堡！挑戰主廚極致手速，單份售價高達 $55',
    cost: 60,
    icon: '👑',
    tag: '新食譜',
    applied: false,
  },
  {
    id: 'extra_table',
    name: '雅座加設 🪑',
    desc: '餐廳新增一張高檔雙人餐桌，可同時接待更多客人',
    cost: 55,
    icon: '🪑',
    tag: '擴充客席',
    applied: false,
  },
  {
    id: 'rep_heal',
    name: '美食家好評報導 💖',
    desc: '立即恢復 1 顆餐廳愛心聲望（上限 3 顆）',
    cost: 35,
    icon: '💖',
    tag: '聲望回復',
    applied: false,
  },
];
